name: pharmalink
description: "A Flutter project."
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  animated_text_kit: ^4.2.2
  flutter:
    sdk: flutter
  flutter_appauth: ^6.0.5
  font_awesome_flutter: 10.6.0
  google_fonts: 6.1.0
  http: ^1.2.1
  introduction_screen: ^3.1.12
  loading_animation_widget: ^1.2.1
  modal_progress_hud_nsn: ^0.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/introductions/
    - assets/images/icons/

  fonts:
    - family: Outfit
      fonts:
        - asset: assets/fonts/Outfit/Outfit-Black.ttf
        - asset: assets/fonts/Outfit/Outfit-ExtraBold.ttf
        - asset: assets/fonts/Outfit/Outfit-ExtraLight.ttf
        - asset: assets/fonts/Outfit/Outfit-Light.ttf
        - asset: assets/fonts/Outfit/Outfit-Medium.ttf
        - asset: assets/fonts/Outfit/Outfit-Regular.ttf
        - asset: assets/fonts/Outfit/Outfit-SemiBold.ttf
        - asset: assets/fonts/Outfit/Outfit-Thin.ttf

    - family: Readex Pro
      fonts:
        - asset: assets/fonts/ReadexPro.ttf

    - family: Plus Jakarta Sans
      fonts:
        - asset: assets/fonts/Plus Jakarta Sans/PlusJakartaSans-Bold.ttf
        - asset: assets/fonts/Plus Jakarta Sans/PlusJakartaSans-BoldItalic.ttf
        - asset: assets/fonts/Plus Jakarta Sans/PlusJakartaSans-ExtraBold.ttf
        - asset: assets/fonts/Plus Jakarta Sans/PlusJakartaSans-ExtraBoldItalic.ttf
        - asset: assets/fonts/Plus Jakarta Sans/PlusJakartaSans-ExtraLight.ttf
        - asset: assets/fonts/Plus Jakarta Sans/PlusJakartaSans-ExtraLightItalic.ttf
        - asset: assets/fonts/Plus Jakarta Sans/PlusJakartaSans-Italic.ttf
        - asset: assets/fonts/Plus Jakarta Sans/PlusJakartaSans-Light.ttf
        - asset: assets/fonts/Plus Jakarta Sans/PlusJakartaSans-LightItalic.ttf
        - asset: assets/fonts/Plus Jakarta Sans/PlusJakartaSans-Medium.ttf
        - asset: assets/fonts/Plus Jakarta Sans/PlusJakartaSans-MediumItalic.ttf
        - asset: assets/fonts/Plus Jakarta Sans/PlusJakartaSans-Regular.ttf
        - asset: assets/fonts/Plus Jakarta Sans/PlusJakartaSans-SemiBold.ttf
        - asset: assets/fonts/Plus Jakarta Sans/PlusJakartaSans-SemiBoldItalic.ttf
