import "package:flutter/material.dart";
import "package:pharmalink/models/input.dart";

const List<String> doctorSpecialtyList = [
  "Accident and emergency medicine",
  "Allergology",
  "Anaesthetics",
  "Biological hematology",
  "Cardiology",
  "Child psychiatry",
  "Clinical biology",
  "Clinical chemistry",
  "Clinical neurophysiology",
  "Clinical radiology",
  "Dental, oral and maxillo-facial surgery",
  "Dermato-venerology",
  "Dermatology",
  "Endocrinology",
  "Gastro-enterologic surgery",
  "Gastroenterology",
  "General hematology",
  "General Practice",
  "General surgery",
  "Geriatrics",
  "Immunology",
  "Infectious diseases",
  "Internal medicine",
  "Laboratory medicine",
  "Maxillo-facial surgery",
  "Microbiology",
  "Nephrology",
  "Neuro-psychiatry",
  "Neurology",
  "Neurosurgery",
  "Nuclear medicine",
  "Obstetrics and gynecology",
  "Occupational medicine",
  "Ophthalmology",
  "Orthopaedics",
  "Otorhinolaryngology",
  "Paediatric surgery",
  "Paediatrics",
  "Pathology",
  "Pharmacology",
  "Physical medicine and rehabilitation",
  "Plastic surgery",
  "Podiatric Medicine",
  "Podiatric Surgery",
  "Psychiatry",
  "Public health and Preventive Medicine",
  "Radiology",
  "Radiotherapy",
  "Respiratory medicine",
  "Rheumatology",
  "Stomatology",
  "Thoracic surgery",
  "Tropical medicine",
  "Urology",
  "Vascular surgery",
  "Venereology",
];
const List<String> doctorDegreeList = [
  "Master's degree",
  "Doctorate",
  "Higher doctorate",
  "Magister degree",
];

List<Input> doctorSignUpModel = [
  Input("First Name", inputType: TextInputType.name, dbName: "fname"),
  Input("Last Name", inputType: TextInputType.name, dbName: "lname"),
  Input("Username", inputType: TextInputType.name, dbName: "username"),
  Input("Password",
      inputType: TextInputType.visiblePassword, dbName: "password"),
  Input("Confirm Password",
      inputType: TextInputType.visiblePassword, dbName: null),
  Input("Email", inputType: TextInputType.emailAddress, dbName: "email"),
  Input("Birth Date", inputType: TextInputType.datetime, dbName: "birthdate"),
  Input("Gender", inputType: TextInputType.name, dbName: "gender"),
  Input("License Number",
      inputType: TextInputType.name, dbName: "license_number"),
  Input("Specialty",
      inputType: TextInputType.none,
      items: doctorSpecialtyList,
      dbName: "specialization"),
  Input("Graduation Date",
      inputType: TextInputType.datetime, dbName: "graduation_date"),
  Input("University", inputType: TextInputType.name, dbName: "university"),
  Input("Degree",
      inputType: TextInputType.none, items: doctorDegreeList, dbName: "degree"),
];
