// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUuO8wMfVaZCCCBd8Ep3k7YBwjP1ux2qg',
    appId: '1:196203930512:android:a8e9cea036d06ad2cec915',
    messagingSenderId: '196203930512',
    projectId: 'pharmalink-333f6',
    storageBucket: 'pharmalink-333f6.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0ebdc6g0Ul0fYoNodvess1hf-l8693uU',
    appId: '1:196203930512:web:1b7b18c90bbd28a6cec915',
    messagingSenderId: '196203930512',
    projectId: 'pharmalink-333f6',
    authDomain: 'pharmalink-333f6.firebaseapp.com',
    storageBucket: 'pharmalink-333f6.appspot.com',
    measurementId: 'G-J9V84JBXR6',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBcvdaYPezRWPcfSYxNsefl_Nq49BcPR2I',
    appId: '1:196203930512:ios:e4215ef538a9699ecec915',
    messagingSenderId: '196203930512',
    projectId: 'pharmalink-333f6',
    storageBucket: 'pharmalink-333f6.appspot.com',
    iosBundleId: 'com.example.pharmalink',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBcvdaYPezRWPcfSYxNsefl_Nq49BcPR2I',
    appId: '1:196203930512:ios:e4215ef538a9699ecec915',
    messagingSenderId: '196203930512',
    projectId: 'pharmalink-333f6',
    storageBucket: 'pharmalink-333f6.appspot.com',
    iosBundleId: 'com.example.pharmalink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0ebdc6g0Ul0fYoNodvess1hf-l8693uU',
    appId: '1:196203930512:web:871eb2630a92c6b4cec915',
    messagingSenderId: '196203930512',
    projectId: 'pharmalink-333f6',
    authDomain: 'pharmalink-333f6.firebaseapp.com',
    storageBucket: 'pharmalink-333f6.appspot.com',
    measurementId: 'G-Y6C71R6DPR',
  );

}